dist: xenial
language: python
python:
- 3.6.9
- '3.7'
install:
- pip install -r requirements.txt
script:
- "/bin/bash -c ci/run.sh"
deploy:
  provider: pypi
  user: __token__
  password:
    secure: RcV348A5XpCSeq0a0fL7SRvE8dZtR2/XmqTiOsup1IDO7inMgTDB1sbm/5F2QHMwWfvLGaNwyUqQ3ySbGuaT022X1s0C76/cv6glHtiYRxI9pwh16dZb0kKVQfGJfn3EdxqD6Ygbd5JnWKIP/K5y7sgGmMDGMHB9SpdhtKt7ViTE/KjZCA4cavosrjyYSnTYVfyHFmB3yYLp2hqKPuUhiJWAznAiQoz0HfkIvoS9mafs6s/QjhLqh4ELz+9U1pHGv5EL7YsUiGYtKuHRRHNI3ZtA9ux83SiZYyV6l5kdT4lnTtrQTQi7xSzE/za8PIIXm/9oihyXEMkleJxfgJXXrBxfdIQxn1KbJUUze+U9Y6x4sWyUxZY0QZaFRXaQENXxEiOI20MXzh351YcfWP/UaeK8EqMVK1IXhtMmo4nMnXmuzNUcE2i+nCqh88nLXyoiGAVkpgvwxo9Q/zFb6txUOy9ruA6WyphCKZ4UxO88h57NpQa8c148Bng3g4wvcpwg6mf1KZgGyQ1MrfpZP5nN5/F69MZxrCmL1udkcRv8YtmophG9RXaF63tt5CMXfAD1ObSazWESWe8wtQIP4GohA84r+JHxCAI/8WBdxvawIOCq6zcBU4BBdMIDTcHYUscRqiGdxjtlzsYxdvGTeGvrzqLUGBtcCZpWEfwogY+D+tQ=
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
