dist: xenial
language: python
python:
- 3.6.9
- '3.7'
install:
- pip install -r requirements.txt
script:
- "/bin/bash -c ci/run.sh"
deploy:
  provider: pypi
  user: __token__
  password:
    secure: EY5Ny/mksGT2zQDnm7KvzOlHxwkDoSr1XRayrScpMn0uXwImjhnjrXBRIXrzNCSBi4deybXe3k2Ib+xRjKqPgGZMXljDpd93V/ygVKwsWAXRHhuCPE3ONidOt+Ughhrh2xza4Z7aJ2llClqPP3C2KWw/31JglRZetQi8UvdzGAE4g3uW+XEuvwMtEu5b267DwrsTkb1LebojCdwRI4T/RaSvzIvtm3RDAHowl+NRGtazFfWLG6eddZJXurJY0Jr8kNtnTziSyo2PMZWY7+bqWScZItRJBu7xA6Ducehd44+YaFcvsS66wTQ4qovzrLhiOt0SHgWzCDLX963E/W2tzB1s5QYgC/L0avMQmIefbCDBT6yMESBhiYtRfNSg3/8jsCDYWzam2QDlT/xVp/KRVcpPyCBEGFS+w9dP6+d9UG8IFD0MflBxX1jvbPmZrRXunXCl/iXKd0zwiMkeGzsaS3AvZ9WLNGHi0nk9ZNb9wa62S2IDdGEewl/qILaEkQSgvQoUnYOK0SUOYSedq1y+qcZR7H7G3zsBc57DoHKJsk2w+gO0f7ZifIkIGnp+gG0vH3MFD7FKK5T8kU7ti9ez5P0/se8JJv22f+6hwcvXHKVgn/UcwWLwMdMRHnzWlVOqo6huwZNK30bpcNHzVOJKI8oikpGKB/PSGc+uPKgYXlM=
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
